# -*- coding: utf-8 -*-
"""KavachPay M6 Zone Risk Clusterer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHJXaDFhSb-StC1kMTlDO_wZ1oUctrfk
"""

# ============================================================
# M6 – Zone Risk Clusterer (Maximum Stability)
# Fixed k=6, UMAP, Bagging, Ensemble, 100 bootstraps
# Output: zone_clusters.csv, zone_cluster_model.pkl
# ============================================================

!pip install scikit-learn hdbscan umap-learn joblib pandas numpy -q

import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
from sklearn.utils import resample
from sklearn.feature_selection import VarianceThreshold
import hdbscan
import umap
import joblib
import warnings
warnings.filterwarnings('ignore')

print("Libraries ready")

# ------------------------------------------------------------
# 1. Load data
# ------------------------------------------------------------
workers = pd.read_csv('workers_final.csv')
claims = pd.read_csv('claims_final.csv')
print(f"Workers: {len(workers)} rows, {workers['zone'].nunique()} zones")
print(f"Claims : {len(claims)} rows")

# ------------------------------------------------------------
# 2. Aggregate base zone features
# ------------------------------------------------------------
zone_df = workers.groupby('zone').agg(
    risk                = ('risk', 'first'),
    social_disruption   = ('social_disruption_exposure', 'first'),
    city_tier           = ('city_tier', 'first'),
    avg_past_claims     = ('past_claims', 'mean'),
    avg_correct_claims  = ('past_correct_claims', 'mean'),
    avg_premium         = ('premium', 'mean'),
    avg_income          = ('internal_income', 'mean'),
    avg_coverage        = ('coverage', 'mean'),
    avg_kavachScore     = ('kavachScore', 'mean'),
    avg_months_active   = ('months_active', 'mean'),
    pct_flagged         = ('policyStatus', lambda x: (x=='flagged').mean()),
    pct_paused          = ('policyStatus', lambda x: (x=='paused').mean()),
    std_premium         = ('premium', 'std'),
    n_workers           = ('customer_id', 'count')
).reset_index()
zone_df['std_premium'] = zone_df['std_premium'].fillna(0)

# Claim‑based features
claims_per_zone = claims.groupby('zone')['claim_id'].count().reset_index(name='total_claims')
workers_per_zone = zone_df[['zone', 'n_workers']].copy()
zone_stats = claims_per_zone.merge(workers_per_zone, on='zone', how='outer').fillna(0)
zone_stats['claim_freq'] = zone_stats['total_claims'] / zone_stats['n_workers'].clip(lower=1)
claim_severity = claims.groupby('zone')['payout_amount'].mean().reset_index(name='avg_payout_per_claim')
zone_stats = zone_stats.merge(claim_severity, on='zone', how='left').fillna(0)
zone_df = zone_df.merge(zone_stats[['zone', 'claim_freq', 'avg_payout_per_claim']], on='zone', how='left').fillna(0)

# ------------------------------------------------------------
# 3. Encode categoricals
# ------------------------------------------------------------
zone_df['risk_enc'] = zone_df['risk'].map({'high':2, 'medium':1, 'low':0}).fillna(1)
zone_df['sde_enc'] = zone_df['social_disruption'].map({'high':2, 'medium':1, 'low':0}).fillna(1)
zone_df['city_tier'] = zone_df['city_tier'].astype(int)

# ------------------------------------------------------------
# 4. Synthetic external features (replace with real data later)
# ------------------------------------------------------------
np.random.seed(42)
rainfall_map = {'high': 1200, 'medium': 800, 'low': 600}
zone_df['avg_rainfall_mm'] = zone_df['risk'].map(rainfall_map) + np.random.normal(0, 100, len(zone_df))
zone_df['avg_rainfall_mm'] = zone_df['avg_rainfall_mm'].clip(lower=300)
zone_df['pop_density'] = 2000 + zone_df['city_tier']*500 + (zone_df['risk'].map({'high':2,'medium':1,'low':0})*200) + np.random.normal(0, 200, len(zone_df))
zone_df['pop_density'] = zone_df['pop_density'].clip(lower=500)
aqi_map = {'high': 180, 'medium': 120, 'low': 80}
zone_df['avg_aqi'] = zone_df['risk'].map(aqi_map) + np.random.normal(0, 20, len(zone_df))
zone_df['avg_aqi'] = zone_df['avg_aqi'].clip(lower=30)

# ------------------------------------------------------------
# 5. Feature engineering (ratios, interactions, logs)
# ------------------------------------------------------------
zone_df['premium_to_income'] = zone_df['avg_premium'] / (zone_df['avg_income'].clip(lower=1) / 4)
zone_df['coverage_ratio'] = zone_df['avg_coverage'] / zone_df['avg_premium'].clip(lower=1)
zone_df['tenure_log'] = np.log1p(zone_df['avg_months_active'])
zone_df['risk_claim_interaction'] = zone_df['risk_enc'] * zone_df['claim_freq']
zone_df['premium_score_interaction'] = zone_df['avg_premium'] * zone_df['avg_kavachScore'] / 1000
zone_df['income_risk_interaction'] = zone_df['avg_income'] * zone_df['risk_enc'] / 1000

FEATURE_COLS = [
    'risk_enc', 'sde_enc', 'city_tier',
    'claim_freq', 'avg_correct_claims', 'avg_payout_per_claim',
    'avg_premium', 'avg_income', 'avg_coverage', 'std_premium',
    'avg_kavachScore', 'avg_months_active',
    'pct_flagged', 'pct_paused',
    'premium_to_income', 'coverage_ratio', 'tenure_log',
    'risk_claim_interaction', 'premium_score_interaction', 'income_risk_interaction',
    'avg_rainfall_mm', 'pop_density', 'avg_aqi'
]

X = zone_df[FEATURE_COLS].copy()
X = X.fillna(X.median())

# Remove low‑variance features
selector = VarianceThreshold(threshold=0.05)
X_high_var = selector.fit_transform(X)
selected_features = [FEATURE_COLS[i] for i in range(len(FEATURE_COLS)) if selector.variances_[i] > 0.05]
print(f"Kept {len(selected_features)} features after variance filtering")

# Remove highly correlated features (correlation >0.9)
corr_matrix = pd.DataFrame(X_high_var, columns=selected_features).corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.9)]
final_features = [col for col in selected_features if col not in to_drop]
print(f"Removed {len(to_drop)} highly correlated features")
X = X[final_features]

# ------------------------------------------------------------
# 6. Scaling (RobustScaler)
# ------------------------------------------------------------
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

# ------------------------------------------------------------
# 7. UMAP for dimensionality reduction (better local structure)
# ------------------------------------------------------------
umap_reducer = umap.UMAP(n_components=10, random_state=42, n_neighbors=15, min_dist=0.1)
X_umap = umap_reducer.fit_transform(X_scaled)
print(f"UMAP reduction applied (10 components)")

# ------------------------------------------------------------
# 8. Define clustering algorithms (FIXED K=6 for stability)
# ------------------------------------------------------------
FIXED_K = 6
algorithms = []

# K-Means
algorithms.append(('KMeans', KMeans(n_clusters=FIXED_K, n_init=100, random_state=42), FIXED_K))

# Agglomerative (ward)
algorithms.append(('AgglomerativeWard', AgglomerativeClustering(n_clusters=FIXED_K, linkage='ward'), FIXED_K))

# Agglomerative (complete)
algorithms.append(('AgglomerativeComplete', AgglomerativeClustering(n_clusters=FIXED_K, linkage='complete'), FIXED_K))

# HDBSCAN (density‑based, tuned for stability)
hdb = hdbscan.HDBSCAN(min_cluster_size=4, min_samples=3, gen_min_span_tree=True)
algorithms.append(('HDBSCAN', hdb, None))

# Gaussian Mixture Model
algorithms.append(('GMM', GaussianMixture(n_components=FIXED_K, random_state=42), FIXED_K))

# ------------------------------------------------------------
# 9. Evaluation with 100 bootstraps (stability)
# ------------------------------------------------------------
def evaluate_clustering(labels, data, n_bootstrap=100):
    if len(set(labels)) < 2:
        return -1, 0
    sil = silhouette_score(data, labels)
    n_points = len(labels)
    stability_sum = 0
    for _ in range(n_bootstrap):
        indices = resample(range(n_points), n_samples=int(0.8*n_points), random_state=None)
        if len(set(labels[indices])) < 2:
            continue
        sil_boot = silhouette_score(data[indices], labels[indices])
        stability_sum += sil_boot
    stability = stability_sum / n_bootstrap
    return sil, stability

results = []
print("\nEvaluating algorithms (100 bootstraps)...")
for name, model, k in algorithms:
    if name == 'HDBSCAN':
        labels = model.fit_predict(X_umap)
        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        if n_clusters < 2:
            continue
        # Remove noise for evaluation
        mask = labels != -1
        if mask.sum() < 10:
            continue
        sil, stab = evaluate_clustering(labels[mask], X_umap[mask])
        results.append({
            'name': name,
            'k': n_clusters,
            'silhouette': sil,
            'stability': stab,
            'labels': labels
        })
        print(f"  {name} -> k={n_clusters}, sil={sil:.4f}, stab={stab:.4f}")
    else:
        labels = model.fit_predict(X_umap)
        sil, stab = evaluate_clustering(labels, X_umap)
        results.append({
            'name': name,
            'k': k,
            'silhouette': sil,
            'stability': stab,
            'labels': labels
        })
        print(f"  {name} k={k:2d} -> sil={sil:.4f}, stab={stab:.4f}")

# ------------------------------------------------------------
# 10. Bagged K-Means (50 subspaces) – additional stability
# ------------------------------------------------------------
print("\nBuilding bagged K‑Means co‑association matrix...")
n_zones = len(zone_df)
co_assoc_bag = np.zeros((n_zones, n_zones))
n_bags = 50
for _ in range(n_bags):
    # Randomly select 80% of features
    feat_idx = np.random.choice(X_umap.shape[1], size=int(0.8*X_umap.shape[1]), replace=False)
    X_sub = X_umap[:, feat_idx]
    km = KMeans(n_clusters=FIXED_K, n_init=20, random_state=None)
    labels = km.fit_predict(X_sub)
    for i in range(n_zones):
        for j in range(i+1, n_zones):
            if labels[i] == labels[j]:
                co_assoc_bag[i,j] += 1
                co_assoc_bag[j,i] += 1
co_assoc_bag /= n_bags

# Cluster the bagged co‑association matrix
from sklearn.cluster import AgglomerativeClustering
dist_bag = 1 - co_assoc_bag
bag_labels = AgglomerativeClustering(n_clusters=FIXED_K, linkage='average').fit_predict(dist_bag)
bag_sil, bag_stab = evaluate_clustering(bag_labels, X_umap)
results.append({
    'name': 'BaggedKMeans',
    'k': FIXED_K,
    'silhouette': bag_sil,
    'stability': bag_stab,
    'labels': bag_labels
})
print(f"  BaggedKMeans -> k={FIXED_K}, sil={bag_sil:.4f}, stab={bag_stab:.4f}")

# ------------------------------------------------------------
# 11. Ensemble on all results (co‑association)
# ------------------------------------------------------------
print("\nBuilding ensemble co‑association matrix...")
co_assoc_ens = np.zeros((n_zones, n_zones))
weights = []
for res in results:
    w = res['stability'] * res['silhouette']  # weight by product
    if w <= 0:
        continue
    weights.append(w)
    labels = res['labels']
    for i in range(n_zones):
        for j in range(i+1, n_zones):
            if labels[i] == labels[j]:
                co_assoc_ens[i,j] += w
                co_assoc_ens[j,i] += w

co_assoc_ens /= sum(weights)
dist_ens = 1 - co_assoc_ens
ensemble_labels = AgglomerativeClustering(n_clusters=FIXED_K, linkage='average').fit_predict(dist_ens)
ens_sil, ens_stab = evaluate_clustering(ensemble_labels, X_umap)
print(f"Ensemble: k={FIXED_K}, sil={ens_sil:.4f}, stab={ens_stab:.4f}")

# ------------------------------------------------------------
# 12. Select best model (highest stability among those with sil>0.25)
# -----------------------------------------------------------
candidates = results + [{'name': 'Ensemble', 'k': FIXED_K, 'silhouette': ens_sil, 'stability': ens_stab, 'labels': ensemble_labels}]
valid = [c for c in candidates if c['silhouette'] > 0.25]
best = max(valid, key=lambda x: x['stability'])

print("\n" + "="*60)
print("BEST MODEL")
print("="*60)
print(f"Algorithm:      {best['name']}")
print(f"Clusters:       {best['k']}")
print(f"Silhouette:     {best['silhouette']:.4f}")
print(f"Stability:      {best['stability']:.4f}")

# ------------------------------------------------------------
# 13. Assign final cluster IDs and reorder by risk
# ------------------------------------------------------------
zone_df['cluster_id'] = best['labels']
cluster_risk = zone_df.groupby('cluster_id')['risk_enc'].mean().sort_values()
risk_order = {old: new for new, old in enumerate(cluster_risk.index)}
zone_df['cluster_id'] = zone_df['cluster_id'].map(risk_order)

# ------------------------------------------------------------
# 14. Save mapping CSV
# ------------------------------------------------------------
output = zone_df[['zone', 'cluster_id']].copy()
output = output.sort_values(['cluster_id', 'zone']).reset_index(drop=True)
output.to_csv('zone_clusters.csv', index=False)
print(f"\nSaved zone_clusters.csv with {len(output)} zones, {output['cluster_id'].nunique()} clusters")
print(output.head(15))

# ------------------------------------------------------------
# 15. Quality assessment
# ------------------------------------------------------------
final_labels = zone_df['cluster_id'].values
final_sil = silhouette_score(X_umap, final_labels)
print("\n" + "="*60)
print("FINAL CLUSTERING QUALITY ASSESSMENT")
print("="*60)
print(f"Silhouette Score:   {final_sil:.4f} (target >0.30)")
print(f"Stability (bootstrap): {best['stability']:.4f} (target >0.65)")
print(f"Number of clusters: {output['cluster_id'].nunique()}")
print(f"Zones per cluster:  {output['cluster_id'].value_counts().min()} - {output['cluster_id'].value_counts().max()}")

if best['stability'] >= 0.65:
    print("\n✅ High stability – excellent for production.")
elif best['stability'] >= 0.55:
    print("\n✅ Moderate stability – acceptable for real-world data.")
else:
    print("\n⚠️ Low stability – consider adding more zones or features.")

# ------------------------------------------------------------
# 16. Cluster profiles
# ------------------------------------------------------------
print("\n" + "="*60)
print("CLUSTER PROFILES (by average risk)")
print("="*60)
cluster_summary = zone_df.groupby('cluster_id').agg(
    n_zones = ('zone', 'count'),
    n_workers = ('n_workers', 'sum'),
    avg_risk = ('risk_enc', 'mean'),
    avg_claims = ('avg_past_claims', 'mean'),
    avg_premium = ('avg_premium', 'mean'),
    avg_score = ('avg_kavachScore', 'mean'),
    zones_sample = ('zone', lambda x: ', '.join(list(x)[:3]))
).reset_index().sort_values('avg_risk')

for _, row in cluster_summary.iterrows():
    risk_label = "HIGH" if row['avg_risk'] > 1.5 else ("MEDIUM" if row['avg_risk'] > 0.5 else "LOW")
    print(f"\nCluster {int(row['cluster_id'])} ({risk_label} RISK):")
    print(f"  Zones: {row['n_zones']}, Workers: {int(row['n_workers'])}")
    print(f"  Avg Risk: {row['avg_risk']:.2f}")
    print(f"  Avg Claims: {row['avg_claims']:.2f}")
    print(f"  Avg Premium: ₹{row['avg_premium']:.0f}")
    print(f"  Avg KavachScore: {row['avg_score']:.0f}")
    print(f"  Sample zones: {row['zones_sample']}...")

# ------------------------------------------------------------
# 17. Save model artifact
# ------------------------------------------------------------
artifact = {
    'model': best['labels'],
    'scaler': scaler,
    'umap': umap_reducer,
    'features': final_features,
    'silhouette': final_sil,
    'stability': best['stability'],
    'n_clusters': output['cluster_id'].nunique(),
    'algorithm': best['name']
}
joblib.dump(artifact, 'zone_cluster_model.pkl')
print("\n✅ Saved: zone_cluster_model.pkl")

print("\n✅ M6 Complete! zone_clusters.csv is ready for M1.")

from google.colab import files
import os

# List of files to download
files_to_download = ['zone_clusters.csv', 'zone_cluster_model.pkl']

for file in files_to_download:
    if os.path.exists(file):
        files.download(file)
        print(f"Downloaded: {file}")
    else:
        print(f"File not found: {file}")

print("Download complete.")

