# -*- coding: utf-8 -*-
"""KavachPay M6 Zone Risk Clusterer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHJXaDFhSb-StC1kMTlDO_wZ1oUctrfk
"""

# ============================================================
# M6 – Zone Risk Clusterer (K‑Means) – Forced k=7
# Input:  workers_final.csv, claims_final.csv
# Output: zone_clusters.csv (zone → cluster_id)
# ============================================================

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.utils import resample
import warnings
warnings.filterwarnings('ignore')

# 1. Load data
workers = pd.read_csv('workers_final.csv')
claims = pd.read_csv('claims_final.csv')
print(f"Workers: {len(workers)} rows, {workers['zone'].nunique()} zones")
print(f"Claims : {len(claims)} rows")

# 2. Aggregate zone features (same as before)
zone_df = workers.groupby('zone').agg(
    risk                = ('risk', 'first'),
    social_disruption   = ('social_disruption_exposure', 'first'),
    city_tier           = ('city_tier', 'first'),
    avg_past_claims     = ('past_claims', 'mean'),
    avg_correct_claims  = ('past_correct_claims', 'mean'),
    avg_premium         = ('premium', 'mean'),
    avg_income          = ('internal_income', 'mean'),
    avg_kavachScore     = ('kavachScore', 'mean'),
    pct_flagged         = ('policyStatus', lambda x: (x=='flagged').mean()),
    n_workers           = ('customer_id', 'count')
).reset_index()

# 3. Add claim frequency
claims_per_zone = claims.groupby('zone')['claim_id'].count().reset_index(name='total_claims')
workers_per_zone = zone_df[['zone', 'n_workers']].copy()
zone_stats = claims_per_zone.merge(workers_per_zone, on='zone', how='outer').fillna(0)
zone_stats['claim_freq'] = zone_stats['total_claims'] / zone_stats['n_workers'].clip(lower=1)
zone_df = zone_df.merge(zone_stats[['zone', 'claim_freq']], on='zone', how='left').fillna(0)

# 4. Encode categoricals
zone_df['risk_enc'] = zone_df['risk'].map({'high':2,'medium':1,'low':0}).fillna(1)
zone_df['sde_enc'] = zone_df['social_disruption'].map({'high':2,'medium':1,'low':0}).fillna(1)
zone_df['city_tier'] = zone_df['city_tier'].astype(int)

# 5. Feature list
CLUSTER_FEATURES = [
    'risk_enc', 'sde_enc', 'city_tier',
    'avg_past_claims', 'avg_correct_claims', 'claim_freq',
    'avg_premium', 'avg_income', 'avg_kavachScore',
    'pct_flagged'
]
X = zone_df[CLUSTER_FEATURES].fillna(0)

# 6. Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 7. (Optional) Compute silhouette for k=2..20 (for information only)
k_range = range(2, 21)
print("\nSilhouette scores for reference:")
for k in k_range:
    km_temp = KMeans(n_clusters=k, n_init=20, random_state=42)
    labels_temp = km_temp.fit_predict(X_scaled)
    sil = silhouette_score(X_scaled, labels_temp)
    print(f"k={k:2d} -> silhouette = {sil:.4f}")

# 8. Force k=7 (business requirement: 5-10 clusters)
FIXED_K = 7
final_km = KMeans(n_clusters=FIXED_K, n_init=100, random_state=42, max_iter=1000)
zone_df['cluster_id'] = final_km.fit_predict(X_scaled)

final_sil = silhouette_score(X_scaled, zone_df['cluster_id'])
print(f"\nFinal model: k={FIXED_K}, Silhouette={final_sil:.4f}")

# 9. Save mapping
output = zone_df[['zone', 'cluster_id']].copy()
output = output.sort_values(['cluster_id', 'zone']).reset_index(drop=True)
output.to_csv('zone_clusters.csv', index=False)
print(f"\nSaved zone_clusters.csv with {len(output)} zones (k={FIXED_K})")
print(output.head(10))

# 10. Quality note
print("\n" + "="*60)
print("CLUSTERING QUALITY ASSESSMENT")
print("="*60)
print(f"Silhouette Score: {final_sil:.4f}")

from google.colab import files
import os

# Check if file exists
if os.path.exists('zone_clusters.csv'):
    files.download('zone_clusters.csv')
    print("Download started: zone_clusters.csv")
else:
    print("File not found. Please run the clustering code first.")

