from flask import Blueprint, request, jsonify
from firebase_admin import firestore
from datetime import datetime, timedelta
from services.verification import trigger_claims_for_zone

disruptions_bp = Blueprint('disruptions', __name__)

@disruptions_bp.route('/active', methods=['GET'])
def get_active_disruptions():
    city = request.args.get('city')
    if not city:
        return jsonify({'error': 'city param required'}), 400

    db  = firestore.client()
    now = datetime.utcnow()
    # Query flattened collection
    docs = db.collection('disruptions').where('city', '==', city).where('active', '==', True).stream()
    alerts = []
    for doc in docs:
        d = doc.to_dict()
        expires_at = d.get('expires_at')
        if expires_at and expires_at.replace(tzinfo=None) > now:
            alerts.append({
                'code': d.get('code'),
                'label': d.get('label'),
                'value': d.get('value'),
                'zone': d.get('zone'),
                'city': d.get('city'),
                'severity': d.get('severity'),
                'time': d.get('time'),
                'color': d.get('color'),
            })
    return jsonify({'alerts': alerts})

@disruptions_bp.route('/simulate', methods=['POST'])
def simulate_disruption():
    """
    Internal/Testing only: Seeds a disruption event and triggers claims pipeline.
    """
    db              = firestore.client()
    data            = request.get_json()
    city            = data.get('city')
    zone            = data.get('zone')
    code            = data.get('code')
    label           = data.get('label')
    value           = data.get('value', '')
    severity        = data.get('severity')
    expires_minutes = data.get('expires_minutes', 120)
    # M3: measured value (rain mm / AQI / Richter)
    measured_value  = float(data.get('measured_value', 0))
    # M7: optional free-text description from tester
    description     = data.get('description', '')

    if not all([city, zone, code, label, severity]):
        return jsonify({'error': 'Missing required fields'}), 400

    # 1. Write to Firestore
    now = datetime.utcnow()
    expires_at = now + timedelta(minutes=expires_minutes)
    
    # Map codes to colors if not provided
    colors = {
        'HRA': '#3B82F6',
        'SAQ': '#8B5CF6',
        'EQK': '#EF4444',
        'FLD': '#06B6D4',
        'LND': '#F59E0B',
        'HWT': '#F97316',
        'CRF': '#DC2626',
        'PND': '#7C3AED',
        'WAR': '#991B1B'
    }
    color = colors.get(code, '#6B7280')

    disruption_id = f"{code}-{now.strftime('%Y%m%d%H%M')}"
    # Write to flat disruptions collection
    db.collection('disruptions').document(disruption_id).set({
        'code': code,
        'label': label,
        'value': value,
        'zone': zone,
        'city': city,
        'severity': severity,
        'time': now.strftime('%I:%M %p'),
        'color': color,
        'active': True,
        'expires_at': expires_at,
        'timestamp': firestore.SERVER_TIMESTAMP
    })

    # 2. Trigger claims pipeline (now passes measured_value + description to M2/M3/M7)
    workers_notified = trigger_claims_for_zone(
        city, zone, code, severity,
        measured_value=measured_value,
        description=description,
    )

    return jsonify({
        'success': True,
        'disruption_id': disruption_id,
        'workers_notified': workers_notified
    })


@disruptions_bp.route('/m4-sync', methods=['POST'])
def m4_sync():
    """
    M4 Disruption Trigger Engine Webhook/Sync.
    Reads the output of the M4 rules engine and triggers the claim pipeline.
    """
    import pandas as pd
    import joblib
    import os

    try:
        # Load M4 Model metadata
        m4_meta = joblib.load('ml_artifacts/disruption_alerts_model.pkl')
        
        # Read the CSV generated by M4
        csv_path = os.path.join('ml_artifacts', m4_meta.get('output_file', 'disaster_alerts.csv'))
        df = pd.read_csv(csv_path)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

    db = firestore.client()
    now = datetime.utcnow()
    disruption_codes = ['HRA', 'MRA', 'LRA', 'STM', 'WND', 'FOG', 'HTV', 'EQK', 'SAQ', 'MAQ', 'FLD', 'CRF', 'LDS', 'PND', 'WAR']
    
    colors = {
        'HRA': '#3B82F6', 'SAQ': '#8B5CF6', 'EQK': '#EF4444', 'FLD': '#06B6D4',
        'LND': '#F59E0B', 'HTV': '#F97316', 'CRF': '#DC2626', 'PND': '#7C3AED', 'WAR': '#991B1B'
    }

    triggered = 0
    new_disruptions = []

    for _, row in df.iterrows():
        city = row['city']
        zone = row['area']
        
        for code in disruption_codes:
            if row.get(code) == 1:
                # Check if it already exists
                existing = list(db.collection('disruptions')
                                .where('city', '==', city)
                                .where('zone', '==', zone)
                                .where('code', '==', code)
                                .where('active', '==', True).stream())
                
                if not existing:
                    severity = 'Severe' if code in ['HRA', 'EQK', 'FLD', 'STM', 'SAQ', 'CRF'] else 'Moderate'
                    disruption_id = f"M4-{code}-{now.strftime('%Y%m%d%H%M')}-{zone[:3]}"
                    
                    # Figure out measured value if any
                    measured_value = 0.0
                    col_map = {'HRA': 'rain_1h_mm', 'MRA': 'rain_1h_mm', 'LRA': 'rain_1h_mm', 'WND': 'wind_kmh', 'STM': 'wind_kmh', 'HTV': 'temp_c', 'SAQ': 'aqi', 'MAQ': 'aqi'}
                    if code in col_map:
                        measured_value = float(row.get(col_map[code], 0))

                    db.collection('disruptions').document(disruption_id).set({
                        'code': code,
                        'label': f"M4 Auto Alert - {code}",
                        'value': str(measured_value),
                        'zone': zone,
                        'city': city,
                        'severity': severity,
                        'time': now.strftime('%I:%M %p'),
                        'color': colors.get(code, '#6B7280'),
                        'active': True,
                        'expires_at': now + timedelta(minutes=120),
                        'timestamp': firestore.SERVER_TIMESTAMP,
                        'source': 'M4_Engine'
                    })

                    # Trigger the pipeline !
                    trigger_claims_for_zone(
                        city, zone, code, severity,
                        measured_value=measured_value,
                        description="Auto-triggered by M4 engine"
                    )

                    triggered += 1
                    new_disruptions.append(disruption_id)

    return jsonify({
        'success': True,
        'triggered_count': triggered,
        'disruptions': new_disruptions
    })
