# -*- coding: utf-8 -*-
"""KavachPay M5 Churn Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Vc-8dfxtGrP_-W3tuLZm3hxWGcMk9Bt
"""

# ============================================================
# KAVACHPAY - M5 Churn Predictor (XGBoost - Production Ready)
# Features: 13 carefully selected features
# Imbalance handling: scale_pos_weight (no SMOTE)
# Tuning: Optuna hyperparameter optimization
# ============================================================

!pip install scikit-learn xgboost optuna joblib pandas numpy -q

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix
import xgboost as xgb
import optuna
import joblib
import warnings
warnings.filterwarnings('ignore')

print("Libraries ready")

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------
df = pd.read_csv('workers_final.csv')
print(f"Loaded: {len(df)} workers, {len(df.columns)} columns")

# ------------------------------------------------------------
# 2. Feature engineering (13 essential features)
# ------------------------------------------------------------
data = df.copy()

# Encodings
data['risk_enc'] = data['risk'].map({'high':2, 'medium':1, 'low':0})
data['policy_flagged'] = (data['policyStatus'] == 'flagged').astype(int)

# Core features
data['honesty_ratio'] = np.where(
    data['past_claims'] > 0,
    data['past_correct_claims'] / data['past_claims'],
    1.0
)

data['premium_to_income'] = data['premium'] / (data['internal_income'].clip(lower=2500) / 4)
data['claim_density'] = np.where(
    data['months_active'] > 0,
    data['past_claims'] / data['months_active'],
    0
)
data['coverage_ratio'] = data['coverage'] / data['premium'].clip(lower=1)

# Log transform
data['tenure_log'] = np.log1p(data['months_active'])

# Interaction feature (most important non-linear effect)
data['premium_score_interaction'] = data['premium'] * data['kavachScore'] / 1000

print("Feature engineering done")

# ------------------------------------------------------------
# 3. Simulate churn label (realistic rules)
# ------------------------------------------------------------
np.random.seed(42)
data['churn_prob_sim'] = 0.15

p75_premium = data['premium'].quantile(0.75)
p50_premium = data['premium'].quantile(0.50)
data.loc[data['premium'] > p75_premium, 'churn_prob_sim'] += 0.25
data.loc[data['premium'].between(p50_premium, p75_premium), 'churn_prob_sim'] += 0.10

p25_score = data['kavachScore'].quantile(0.25)
p50_score = data['kavachScore'].quantile(0.50)
data.loc[data['kavachScore'] < p25_score, 'churn_prob_sim'] += 0.25
data.loc[data['kavachScore'].between(p25_score, p50_score), 'churn_prob_sim'] += 0.10

data.loc[data['months_active'] < 3, 'churn_prob_sim'] += 0.30
data.loc[data['months_active'].between(3, 6), 'churn_prob_sim'] += 0.15
data.loc[data['months_active'] > 24, 'churn_prob_sim'] -= 0.15

data.loc[data['policyStatus'] == 'flagged', 'churn_prob_sim'] += 0.35
data.loc[data['risk'] == 'high', 'churn_prob_sim'] += 0.08
data.loc[data['city_tier'] == 2, 'churn_prob_sim'] += 0.08
data.loc[(data['past_claims'] == 0) & (data['months_active'] > 6), 'churn_prob_sim'] += 0.12
data.loc[data['honesty_ratio'] < 0.5, 'churn_prob_sim'] += 0.15
data.loc[data['premium_to_income'] > 0.06, 'churn_prob_sim'] += 0.12
data.loc[data['claim_density'] > 0.3, 'churn_prob_sim'] += 0.10

# Interaction adjustment
data.loc[(data['premium'] > p75_premium) & (data['kavachScore'] < p25_score), 'churn_prob_sim'] += 0.10

data['churn_prob_sim'] = data['churn_prob_sim'].clip(0.02, 0.98)
data['churned'] = np.random.binomial(1, data['churn_prob_sim'])

print(f"Simulated churn rate: {data['churned'].mean()*100:.1f}%")

# ------------------------------------------------------------
# 4. Prepare features (13 essential features)
# ------------------------------------------------------------
FEATURE_COLS = [
    'premium',                    # What they pay
    'kavachScore',                # Trust score
    'months_active',              # Tenure
    'past_claims',                # Claims filed
    'city_tier',                  # Metro vs non-metro
    'honesty_ratio',              # % of honest claims
    'risk_enc',                   # Zone risk level
    'premium_to_income',          # Affordability stress
    'claim_density',              # Claims per month
    'coverage_ratio',             # Value for money
    'premium_score_interaction',  # Premium × Score effect
    'tenure_log',                 # Log tenure
    'policy_flagged'              # Flagged status
]

X = data[FEATURE_COLS]
y = data['churned']

print(f"\nFeatures: {len(FEATURE_COLS)}")
for i, col in enumerate(FEATURE_COLS, 1):
    print(f"  {i:2}. {col}")

# ------------------------------------------------------------
# 5. Train-test split
# ------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale features (helps XGBoost converge faster)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"\nTrain size: {len(X_train)} (churn rate {y_train.mean()*100:.1f}%)")
print(f"Test size: {len(X_test)} (churn rate {y_test.mean()*100:.1f}%)")

# ------------------------------------------------------------
# 6. XGBoost with scale_pos_weight (NO SMOTE)
# ------------------------------------------------------------
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"\nScale pos weight: {scale_pos_weight:.2f} (XGBoost handles imbalance automatically)")

# ------------------------------------------------------------
# 7. Optuna hyperparameter tuning
# ------------------------------------------------------------
def objective(trial):
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'auc',
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 2),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2),
        'scale_pos_weight': scale_pos_weight,
        'random_state': 42,
        'verbosity': 0
    }

    cv_scores = cross_val_score(
        xgb.XGBClassifier(**params),
        X_train_scaled, y_train,
        cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
        scoring='roc_auc',
        n_jobs=-1
    )
    return cv_scores.mean()

print("\nRunning Optuna hyperparameter tuning (30 trials)...")
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=30, show_progress_bar=True)

best_params = study.best_params
print(f"\nBest parameters:")
for key, value in best_params.items():
    print(f"  {key}: {value}")
print(f"Best CV AUC: {study.best_value:.4f}")

# ------------------------------------------------------------
# 8. Train final model
# ------------------------------------------------------------
best_params['objective'] = 'binary:logistic'
best_params['eval_metric'] = 'auc'
best_params['scale_pos_weight'] = scale_pos_weight
best_params['random_state'] = 42
best_params['verbosity'] = 0

final_model = xgb.XGBClassifier(**best_params)
final_model.fit(X_train_scaled, y_train)

# ------------------------------------------------------------
# 9. Evaluate
# ------------------------------------------------------------
y_pred_proba = final_model.predict_proba(X_test_scaled)[:, 1]
test_auc = roc_auc_score(y_test, y_pred_proba)
print(f"\nTest AUC: {test_auc:.4f}")

y_pred = final_model.predict(X_test_scaled)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Stayed', 'Churned']))

# ------------------------------------------------------------
# 10. Feature importance
# ------------------------------------------------------------
importance_df = pd.DataFrame({
    'feature': FEATURE_COLS,
    'importance': final_model.feature_importances_
}).sort_values('importance', ascending=False)

print("\nFeature Importance (higher = more important):")
for i, row in importance_df.iterrows():
    print(f"  {row['feature']:<25} {row['importance']:.4f}")

# ------------------------------------------------------------
# 11. Save model
# ------------------------------------------------------------
artifact = {
    'model': final_model,
    'scaler': scaler,
    'feature_cols': FEATURE_COLS,
    'best_params': best_params,
    'test_auc': test_auc
}
joblib.dump(artifact, 'churn_model_final.pkl')
print("\nSaved: churn_model_final.pkl")

# ------------------------------------------------------------
# 12. Generate predictions CSV
# ------------------------------------------------------------
X_full_scaled = scaler.transform(X)
probs = final_model.predict_proba(X_full_scaled)[:, 1]

buckets = []
for p in probs:
    if p < 0.20:
        buckets.append('Low')
    elif p < 0.50:
        buckets.append('Medium')
    else:
        buckets.append('High')

output_df = pd.DataFrame({
    'customer_id': data['customer_id'],
    'churn_probability': probs,
    'churn_risk_bucket': buckets
})
output_df = output_df.round({'churn_probability': 4})

output_df.to_csv('churn_predictions_final.csv', index=False)
print("Saved: churn_predictions_final.csv")
print(output_df.head(10))

# ------------------------------------------------------------
# 13. Prediction function for backend
# ------------------------------------------------------------
def predict_churn(worker_dict):
    """
    Predicts churn probability for a single worker.
    Required keys: premium, kavachScore, months_active, past_claims,
                   past_correct_claims, city_tier, risk, policyStatus,
                   internal_income, avg_daily_deliveries, coverage, age
    """
    artifact = joblib.load('churn_model_final.pkl')
    model = artifact['model']
    scaler = artifact['scaler']
    cols = artifact['feature_cols']

    # Compute derived features
    past_claims = worker_dict.get('past_claims', 0)
    past_correct = worker_dict.get('past_correct_claims', 0)
    honesty = (past_correct / past_claims) if past_claims > 0 else 1.0

    inc = max(worker_dict.get('internal_income', 2500), 1)
    premium_to_income = worker_dict['premium'] / (inc / 4)
    claim_density = worker_dict.get('past_claims', 0) / max(worker_dict.get('months_active', 1), 0.1)
    coverage_ratio = worker_dict.get('coverage', 1000) / max(worker_dict.get('premium', 50), 1)
    tenure_log = np.log1p(worker_dict.get('months_active', 0))
    premium_score_interaction = worker_dict['premium'] * worker_dict.get('kavachScore', 750) / 1000
    risk_enc = {'high':2, 'medium':1, 'low':0}.get(worker_dict.get('risk', 'medium'), 1)
    policy_flagged = int(worker_dict.get('policyStatus', 'active') == 'flagged')

    features = {
        'premium': worker_dict['premium'],
        'kavachScore': worker_dict.get('kavachScore', 750),
        'months_active': worker_dict.get('months_active', 0),
        'past_claims': past_claims,
        'city_tier': worker_dict.get('city_tier', 1),
        'honesty_ratio': honesty,
        'risk_enc': risk_enc,
        'premium_to_income': premium_to_income,
        'claim_density': claim_density,
        'coverage_ratio': coverage_ratio,
        'premium_score_interaction': premium_score_interaction,
        'tenure_log': tenure_log,
        'policy_flagged': policy_flagged,
    }

    row = np.array([[features[col] for col in cols]])
    row_scaled = scaler.transform(row)
    prob = model.predict_proba(row_scaled)[0, 1]
    return round(float(prob), 3)

print("\n✅ Prediction function ready: predict_churn()")
print(f"✅ Final Test AUC: {test_auc:.4f}")
print(f"✅ Model saved: churn_model_final.pkl")

# ============================================================
# Generate churn_predictor.py (backend module for XGBoost)
# ============================================================

predictor_code = '''# churn_predictor.py
# M5 – Churn Prediction Model for KavachPay (XGBoost)
# Usage: from churn_predictor import predict_churn

import joblib
import numpy as np

# Load model artifacts once (global)
_artifact = joblib.load('churn_model_final.pkl')
_model = _artifact['model']
_scaler = _artifact['scaler']
_feature_cols = _artifact['feature_cols']

def predict_churn(worker_dict):
    """
    Predicts churn probability (0-1) for a single worker.

    Required keys in worker_dict:
        premium, kavachScore, months_active, past_claims, past_correct_claims,
        city_tier, risk, policyStatus, internal_income, coverage, age
    """
    # Get raw values
    premium = worker_dict['premium']
    kavachScore = worker_dict['kavachScore']
    months_active = worker_dict['months_active']
    past_claims = worker_dict.get('past_claims', 0)
    past_correct = worker_dict.get('past_correct_claims', 0)
    city_tier = worker_dict['city_tier']
    risk = worker_dict.get('risk', 'medium')
    policyStatus = worker_dict.get('policyStatus', 'active')
    internal_income = worker_dict.get('internal_income', 2500)
    coverage = worker_dict.get('coverage', 1000)
    age = worker_dict.get('age', 28)

    # Compute derived features (must match training)

    # 1. honesty_ratio
    honesty_ratio = (past_correct / past_claims) if past_claims > 0 else 1.0

    # 2. premium_to_income (affordability)
    inc = max(internal_income, 1)
    premium_to_income = premium / (inc / 4)

    # 3. claim_density (claims per month)
    claim_density = past_claims / max(months_active, 0.1)

    # 4. coverage_ratio (value for money)
    coverage_ratio = coverage / max(premium, 1)

    # 5. tenure_log (log transform of tenure)
    tenure_log = np.log1p(months_active)

    # 6. premium_score_interaction (non-linear effect)
    premium_score_interaction = premium * kavachScore / 1000

    # 7. risk_enc (encode risk to numeric)
    risk_enc = {'high': 2, 'medium': 1, 'low': 0}.get(risk, 1)

    # 8. policy_flagged (flagged status)
    policy_flagged = 1 if policyStatus == 'flagged' else 0

    # Build feature dictionary in exact order as training
    features = {
        'premium': premium,
        'kavachScore': kavachScore,
        'months_active': months_active,
        'past_claims': past_claims,
        'city_tier': city_tier,
        'honesty_ratio': honesty_ratio,
        'risk_enc': risk_enc,
        'premium_to_income': premium_to_income,
        'claim_density': claim_density,
        'coverage_ratio': coverage_ratio,
        'premium_score_interaction': premium_score_interaction,
        'tenure_log': tenure_log,
        'policy_flagged': policy_flagged,
    }

    # Order features exactly as in training
    row = [[features[col] for col in _feature_cols]]
    row_scaled = _scaler.transform(row)
    prob = _model.predict_proba(row_scaled)[0, 1]
    return round(float(prob), 3)

if __name__ == '__main__':
    sample = {
        'premium': 80,
        'kavachScore': 820,
        'months_active': 24,
        'past_claims': 2,
        'past_correct_claims': 2,
        'city_tier': 1,
        'risk': 'low',
        'policyStatus': 'active',
        'internal_income': 4800,
        'coverage': 2000,
        'age': 34
    }
    print(f"Churn probability: {predict_churn(sample)}")
'''

with open('churn_predictor.py', 'w') as f:
    f.write(predictor_code)
print("Created: churn_predictor.py (updated for XGBoost model)")

from google.colab import files

# Download the new XGBoost model file
files.download('churn_model_final.pkl')

# Download the updated backend module
files.download('churn_predictor.py')

# Download the new predictions CSV
files.download('churn_predictions_final.csv')

print("✅ All files downloaded:")
print("   - churn_model_final.pkl (XGBoost model)")
print("   - churn_predictor.py (backend module)")
print("   - churn_predictions_final.csv (batch predictions)")

