# -*- coding: utf-8 -*-
"""KavachPay Model M7 - Quantile Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swbEYpebuNZHsP7GaO4NG0qXk6tJHoN2
"""

# ============================================================
# KAVACHPAY — M3 Income Loss Estimator (PRODUCTION READY)
# Trains quantile regression models (P10, P50, P90) on 10k rows.
# Outputs: income_loss_qr.pkl, kavach_predict.py
# ============================================================

# Install required packages (uncomment if needed)
# !pip install lightgbm optuna scikit-learn joblib pandas numpy -q

import os, warnings
from datetime import datetime
import numpy as np
import pandas as pd
import joblib
import lightgbm as lgb
import optuna
from optuna.pruners import MedianPruner
from optuna.samplers import TPESampler
from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_absolute_error

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings("ignore")
np.random.seed(42)

# ========================= CONFIGURATION =========================
N_TRIALS   = 75          # trials per quantile (optimal for 10k rows)
N_SPLITS   = 5
EARLY_STOP = 60
QUANTILES  = [0.10, 0.50, 0.90]
SMOOTH_K   = 15

CKPT_FEAT  = "m3_ckpt_features.pkl"
CKPT_SPLIT = "m3_ckpt_split.pkl"
CKPT_MDLS  = "m3_ckpt_models.pkl"
OPTUNA_DB  = "sqlite:///m3_optuna.db"
OUT_PKL    = "income_loss_qr.pkl"
OUT_PY     = "kavach_predict.py"

print("Libraries ready")

# ========================= LOAD DATA =============================
claims = pd.read_csv("claims_final.csv")
workers = pd.read_csv("workers_final.csv")
print(f"Claims: {claims.shape}, Workers: {workers.shape}")

claims.columns = claims.columns.str.strip()
workers.columns = workers.columns.str.strip()

# Standardise wind column name
if "wind_kmh" in claims.columns:
    claims = claims.rename(columns={"wind_kmh": "wind_speed"})
elif "wind_kwh" in claims.columns:
    claims = claims.rename(columns={"wind_kwh": "wind_speed"})

# Sensor columns that may exist
SENSOR_COLS = [c for c in ["rain_mm", "aqi_val", "wind_speed",
                           "vis_m", "temp_c", "mag", "measured_value"]
               if c in claims.columns]
print(f"Sensors found: {SENSOR_COLS}")

# Merge on employee_id (present in both)
merge_col = "employee_id" if "employee_id" in workers.columns else "customer_id"
df = claims.merge(workers, on=merge_col, how="left", suffixes=("", "_worker"))
print(f"Merged shape: {df.shape}")

# ========================= CLEAN TARGET ===========================
df["payout_amount"] = pd.to_numeric(df["payout_amount"], errors="coerce")
# Keep only paid/pending claims, exclude fraud and excluded
if "status" in df.columns:
    df = df[df["status"].isin(["paid", "pending"])]
if "fraud_flag" in df.columns:
    df = df[df["fraud_flag"] != 1]
    df = df[df["fraud_flag"] != True]
if "is_excluded" in df.columns:
    df = df[df["is_excluded"] != 1]
    df = df[df["is_excluded"] != True]
df = df.dropna(subset=["payout_amount"])
df = df[df["payout_amount"] > 0]
print(f"After cleaning: {len(df)} rows")

# If too few rows, warn but continue
if len(df) < 1000:
    print("WARNING: Very few clean rows. Model may be unreliable.")

# ========================= FEATURE ENGINEERING ===================
# Duration map for disruption codes
DURATION_MAP = {
    "LRA":4, "MRA":6, "HRA":8, "MAQ":12, "SAQ":12, "STM":4,
    "WND":6, "FLD":24, "CRF":24, "LDS":24, "FOG":6, "HTV":8,
    "EQK":2, "PND":0, "WAR":0
}
ALL_CODES = list(DURATION_MAP.keys())

# Ensure disruption_code exists
if "disruption_code" not in df.columns:
    # Try to map from 'category' column
    cat_map = {"RAI":"HRA", "AQI":"SAQ", "FLD":"FLD", "CRF":"CRF",
               "EQK":"EQK", "STM":"STM", "LDS":"LDS", "HTV":"HTV",
               "FOG":"FOG", "WND":"WND"}
    df["disruption_code"] = df["category"].map(cat_map).fillna("HRA")
df["disruption_hours"] = df["disruption_code"].map(DURATION_MAP).fillna(6)

# Temporal features
df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce", dayfirst=True)
df["day_of_week"] = df["created_at"].dt.dayofweek.fillna(0).astype(int)
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)
df["month"] = df["created_at"].dt.month.fillna(6).astype(int)
df["quarter"] = df["created_at"].dt.quarter.fillna(2).astype(int)
df["is_monsoon"] = df["month"].isin([6,7,8,9]).astype(int)
for col, p in [("day_of_week",7), ("month",12)]:
    df[f"{col}_sin"] = np.sin(2*np.pi*df[col]/p)
    df[f"{col}_cos"] = np.cos(2*np.pi*df[col]/p)

# Categorical encodings
risk_map = {"high":2, "medium":1, "low":0}
plat_map = {"Zomato":1, "Swiggy":0}
sev_map = {"Severe":2, "Moderate":1, "Minor":0}
sde_map = {"high":2, "medium":1, "low":0}
df["risk_enc"] = df["risk"].map(risk_map).fillna(1)
df["platform_enc"] = df["platform"].map(plat_map).fillna(0)
df["severity_enc"] = df["severity"].map(sev_map).fillna(1)
df["sde_enc"] = df["social_disruption_exposure"].map(sde_map).fillna(1)

# Typical workdays (string like "Mon,Tue,..." -> count)
if "typical_workdays" in df.columns:
    df["workdays_count"] = df["typical_workdays"].astype(str).apply(
        lambda x: len(x.split(",")) if "," in x else 5
    ).clip(1,7)
else:
    df["workdays_count"] = 5

# Numeric imputation
num_cols = ["avg_daily_deliveries", "avg_weekly_income", "avg_daily_distance",
            "kavachScore", "months_active", "past_claims", "past_correct_claims",
            "total_paid", "coverage", "premium", "risk_multiplier", "age",
            "city_tier", "layers_passed", "distance", "flag_count"]
for col in num_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].fillna(df[col].median())
df["avg_daily_deliveries"] = df["avg_daily_deliveries"].clip(lower=1)

# Sensor imputation & winsorisation
for col in SENSOR_COLS:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    p99 = df[col].quantile(0.99)
    df[col] = df[col].clip(upper=p99).fillna(df[col].median())

# Derived features
df["claim_accuracy"] = df["past_correct_claims"] / (df["past_claims"] + 1)
df["daily_income_est"] = df["avg_weekly_income"] / 6
df["hourly_income_est"] = df["daily_income_est"] / 8
df["coverage_income_ratio"] = df["coverage"] / (df["avg_weekly_income"] + 1)
df["premium_income_ratio"] = df["premium"] / (df["avg_weekly_income"] + 1)
df["experience_score"] = np.log1p(df["months_active"]) * df["kavachScore"] / 900
df["delivery_density"] = df["avg_daily_deliveries"] / (df["avg_daily_distance"] + 1)
df["loss_per_delivery"] = df["total_paid"] / (df["past_claims"] + 1)
df["honesty_score"] = df["claim_accuracy"] * df["kavachScore"] / 900
df["disruption_severity_score"] = (df["disruption_hours"] *
                                   (1 + df["risk_enc"]*0.5) *
                                   (1 + df["severity_enc"]*0.3))

# Rule‑based loss estimate (prior)
df["rule_based_loss"] = (df["daily_income_est"] * df["disruption_hours"] / 8 *
                         (df["severity_enc"] * 0.35)).clip(lower=0)

# Interactions
df["delivery_x_hours"] = df["avg_daily_deliveries"] * df["disruption_hours"]
df["severity_x_delivery"] = df["severity_enc"] * df["avg_daily_deliveries"]
df["severity_x_hours"] = df["severity_enc"] * df["disruption_hours"]
df["income_x_disruption"] = df["daily_income_est"] * df["disruption_hours"]
df["income_x_severity"] = df["daily_income_est"] * df["severity_enc"]
df["coverage_x_severity"] = df["coverage"] * df["severity_enc"]
df["risk_x_duration"] = df["risk_enc"] * df["disruption_hours"]
if "rain_mm" in df.columns:
    df["delivery_x_rain"] = df["avg_daily_deliveries"] * df["rain_mm"]
    df["risk_x_rain"] = df["risk_enc"] * df["rain_mm"]
if "aqi_val" in df.columns:
    df["delivery_x_aqi"] = df["avg_daily_deliveries"] * df["aqi_val"]
    df["risk_x_aqi"] = df["risk_enc"] * df["aqi_val"]
if "wind_speed" in df.columns:
    df["risk_x_wind"] = df["risk_enc"] * df["wind_speed"]

# Target encoding (OOF, no leakage)
global_mean = df["payout_amount"].mean()
kf_enc = KFold(n_splits=5, shuffle=True, random_state=0)
df["dc_target_enc"] = global_mean
for tr_idx, val_idx in kf_enc.split(df):
    agg = df.iloc[tr_idx].groupby("disruption_code")["payout_amount"].agg(["mean","count"])
    smooth = (agg["mean"]*agg["count"] + global_mean*SMOOTH_K) / (agg["count"]+SMOOTH_K)
    df.iloc[val_idx, df.columns.get_loc("dc_target_enc")] = (
        df.iloc[val_idx]["disruption_code"].map(smooth).fillna(global_mean)
    )

# One‑hot encode disruption codes
dummies = pd.get_dummies(df["disruption_code"], prefix="dc")
for code in ALL_CODES:
    if f"dc_{code}" not in dummies.columns:
        dummies[f"dc_{code}"] = 0
dc_cols = [f"dc_{c}" for c in ALL_CODES]
dummies = dummies[dc_cols]
df = pd.concat([df, dummies], axis=1)

# Build final feature list
base_features = [
    "avg_daily_deliveries", "platform_enc", "risk_enc", "months_active",
    "workdays_count", "past_claims", "past_correct_claims", "claim_accuracy",
    "kavachScore", "avg_weekly_income", "avg_daily_distance", "daily_income_est",
    "hourly_income_est", "coverage", "coverage_income_ratio", "premium",
    "premium_income_ratio", "risk_multiplier", "sde_enc", "total_paid",
    "experience_score", "delivery_density", "loss_per_delivery", "honesty_score",
    "disruption_hours", "severity_enc", "disruption_severity_score",
    "day_of_week", "is_weekend", "month", "quarter", "is_monsoon",
    "day_of_week_sin", "day_of_week_cos", "month_sin", "month_cos",
    *SENSOR_COLS,
    "delivery_x_hours", "severity_x_delivery", "severity_x_hours",
    "income_x_disruption", "income_x_severity", "coverage_x_severity",
    "risk_x_duration", "rule_based_loss", "dc_target_enc"
]
# Add interaction features that exist
interactions = ["delivery_x_rain", "risk_x_rain", "delivery_x_aqi", "risk_x_aqi", "risk_x_wind"]
base_features += [c for c in interactions if c in df.columns]
base_features += dc_cols

# Keep only valid features
feature_cols = []
for f in base_features:
    if f in df.columns and df[f].std() > 0:
        feature_cols.append(f)
print(f"Total features: {len(feature_cols)}")

# ========================= TRAIN/TEST SPLIT =======================
X_all = df[feature_cols].astype(float)
y_all = df["payout_amount"].astype(float)
y_log = np.log1p(y_all)

X_train, X_test, y_train_log, y_test_log = train_test_split(
    X_all, y_log, test_size=0.15, random_state=42, shuffle=True
)
y_train_raw = np.expm1(y_train_log)
y_test_raw = np.expm1(y_test_log)

# No‑leak target encoding for test set (use training means)
train_dc = df.loc[X_train.index, "disruption_code"].values
test_dc = df.loc[X_test.index, "disruption_code"].values
dc_means = {}
for code in ALL_CODES:
    mask = (train_dc == code)
    cnt = mask.sum()
    if cnt > 0:
        mu = y_train_raw[mask].mean()
        dc_means[code] = (mu*cnt + global_mean*SMOOTH_K) / (cnt + SMOOTH_K)
    else:
        dc_means[code] = global_mean

X_test = X_test.copy()
if "dc_target_enc" in X_test.columns:
    X_test["dc_target_enc"] = [dc_means.get(c, global_mean) for c in test_dc]

# Scaling (RobustScaler handles outliers)
scaler = RobustScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=feature_cols, index=X_train.index)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=feature_cols, index=X_test.index)

print(f"Train size: {len(X_train_scaled)}, Test size: {len(X_test_scaled)}")

# ========================= OPTUNA TUNING ==========================
def pinball(q, y_true, y_pred):
    e = y_true - y_pred
    return np.mean(np.where(e >= 0, q*e, (q-1)*e))

def make_objective(q, X_tr, y_tr_log):
    def objective(trial):
        params = {
            "objective": "quantile", "alpha": q, "metric": "quantile",
            "verbosity": -1, "boosting_type": "gbdt",
            "n_estimators": trial.suggest_int("n_estimators", 300, 3000),
            "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.15, log=True),
            "num_leaves": trial.suggest_int("num_leaves", 20, 256),
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 10.0, log=True),
            "min_split_gain": trial.suggest_float("min_split_gain", 0.0, 3.0),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 1.0),
        }
        kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
        losses = []
        for tr_idx, val_idx in kf.split(X_tr):
            Xt, yt = X_tr.iloc[tr_idx], y_tr_log.iloc[tr_idx]
            Xv, yv = X_tr.iloc[val_idx], y_tr_log.iloc[val_idx]
            m = lgb.LGBMRegressor(**params)
            m.fit(Xt, yt, eval_set=[(Xv, yv)],
                  callbacks=[lgb.early_stopping(EARLY_STOP, verbose=False),
                             lgb.log_evaluation(-1)])
            pred_raw = np.maximum(0, np.expm1(m.predict(Xv)))
            y_raw = np.expm1(yv.values)
            losses.append(pinball(q, y_raw, pred_raw))
        return np.mean(losses)
    return objective

best_params = {}
for q in QUANTILES:
    study_name = f"kavach_q{int(q*100)}"
    study = optuna.create_study(
        study_name=study_name, direction="minimize",
        sampler=TPESampler(seed=42, n_startup_trials=20),
        pruner=MedianPruner(n_startup_trials=20, n_warmup_steps=3),
        storage=OPTUNA_DB, load_if_exists=True
    )
    done = sum(1 for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE)
    rem = max(0, N_TRIALS - done)
    if rem > 0:
        print(f"Tuning Q={q} ({done} done, {rem} left)...")
        study.optimize(make_objective(q, X_train_scaled, y_train_log),
                       n_trials=rem, show_progress_bar=True)
    best_params[q] = study.best_params
    print(f"Q={q} best pinball = {study.best_value:.4f}")

# ========================= FINAL MODELS ============================
X_tr_f, X_val_f, y_tr_f, y_val_f = train_test_split(
    X_train_scaled, y_train_log, test_size=0.12, random_state=7
)
models = {}
for q in QUANTILES:
    print(f"Training Q={q}...")
    params = {"objective": "quantile", "alpha": q, "metric": "quantile",
              "verbosity": -1, "boosting_type": "gbdt", **best_params[q]}
    m = lgb.LGBMRegressor(**params)
    m.fit(X_tr_f, y_tr_f, eval_set=[(X_val_f, y_val_f)],
          callbacks=[lgb.early_stopping(EARLY_STOP+20, verbose=False),
                     lgb.log_evaluation(100)])
    models[q] = m
    print(f"  best_iteration = {m.best_iteration_}")

def predict_quantiles(X):
    p10 = np.maximum(0, np.expm1(models[0.10].predict(X)))
    p50 = np.maximum(0, np.expm1(models[0.50].predict(X)))
    p90 = np.maximum(0, np.expm1(models[0.90].predict(X)))
    p50 = np.maximum(p10, p50)
    p90 = np.maximum(p50, p90)
    return p10, p50, p90

# ========================= EVALUATION ==============================
p10, p50, p90 = predict_quantiles(X_test_scaled)
y_true = y_test_raw.values

def winkler_score(y, lower, upper, alpha=0.20):
    width = upper - lower
    miss_low = (2/alpha) * np.maximum(0, lower - y)
    miss_high = (2/alpha) * np.maximum(0, y - upper)
    return np.mean(width + miss_low + miss_high)

print("\n" + "="*70)
print("TEST SET EVALUATION")
print("="*70)
for label, pred, q in [("P10", p10, 0.10), ("P50", p50, 0.50), ("P90", p90, 0.90)]:
    mae = mean_absolute_error(y_true, pred)
    pb = pinball(q, y_true, pred)
    cov = np.mean(y_true <= pred)
    rel = mae / y_true.mean() * 100
    print(f"{label}: MAE={mae:6.1f} ({rel:4.1f}%) | Pinball={pb:.4f} | Coverage={cov:.1%} (target={q:.0%})")

w80 = winkler_score(y_true, p10, p90, alpha=0.20)
cov80 = np.mean((y_true >= p10) & (y_true <= p90))
print(f"\n80% interval: Winkler={w80:.1f} | Coverage={cov80:.1%} (target=80%)")

# OOF unbiased estimate
print("\nComputing 5‑fold OOF (honest estimate)...")
oof_p50 = np.zeros(len(X_all))
kf_oof = KFold(n_splits=5, shuffle=True, random_state=42)
for fold, (tr_idx, val_idx) in enumerate(kf_oof.split(X_all)):
    Xtr = X_all.iloc[tr_idx]
    ytr = y_log.iloc[tr_idx]
    Xval = X_all.iloc[val_idx]
    Xtr_s, Xval_s, ytr_s, yval_s = train_test_split(Xtr, ytr, test_size=0.12, random_state=fold)
    Xtr_s_scaled = scaler.transform(Xtr_s)
    Xval_s_scaled = scaler.transform(Xval_s)
    m_oof = lgb.LGBMRegressor(**{"objective":"quantile","alpha":0.50,"metric":"quantile",
                                 "verbosity":-1,"boosting_type":"gbdt", **best_params[0.50]})
    m_oof.fit(Xtr_s_scaled, ytr_s, eval_set=[(Xval_s_scaled, yval_s)],
              callbacks=[lgb.early_stopping(EARLY_STOP, verbose=False)])
    oof_p50[val_idx] = np.maximum(0, np.expm1(m_oof.predict(scaler.transform(Xval))))
    print(f"  Fold {fold+1}/5 done")
oof_mae = mean_absolute_error(y_all, oof_p50)
print(f"OOF P50 MAE: Rs.{oof_mae:.1f} ({oof_mae/y_all.mean()*100:.1f}%)")

# Feature importance (P50)
imp = pd.Series(models[0.50].feature_importances_, index=feature_cols).sort_values(ascending=False)
print("\nTop 15 features (P50 model):")
for f, v in imp.head(15).items():
    print(f"  {f:<35} {v}")

# ========================= SAVE ARTIFACT ===========================
artifact = {
    "models": models,
    "scaler": scaler,
    "feature_cols": feature_cols,
    "best_params": best_params,
    "duration_map": DURATION_MAP,
    "disruption_codes": ALL_CODES,
    "sensor_cols": SENSOR_COLS,
    "dc_means": dc_means,
    "global_mean": global_mean,
    "smooth_k": SMOOTH_K,
    "quantiles": QUANTILES,
    "metadata": {
        "model_type": "LightGBM Quantile Regression",
        "trained_at": datetime.now().isoformat(),
        "n_train": len(X_train_scaled),
        "n_test": len(X_test_scaled),
        "n_features": len(feature_cols),
        "log_transform": True,
        "p50_mae_test": mean_absolute_error(y_true, p50),
        "p50_mae_oof": oof_mae,
        "winkler_80pct": w80,
        "calibration": {str(q): np.mean(y_true <= pred) for q, pred in zip(QUANTILES, [p10, p50, p90])}
    }
}
joblib.dump(artifact, OUT_PKL, compress=3)
print(f"\nSaved: {OUT_PKL}")

# ========================= GENERATE INFERENCE MODULE ===============
inference_code = '''# kavach_predict.py
# Income loss estimator inference module

import numpy as np
import pandas as pd
import joblib
from functools import lru_cache

@lru_cache(maxsize=1)
def _load_artifact(path="income_loss_qr.pkl"):
    return joblib.load(path)

_DURATION_MAP = {
    "LRA":4,"MRA":6,"HRA":8,"MAQ":12,"SAQ":12,"STM":4,
    "WND":6,"FLD":24,"CRF":24,"LDS":24,"FOG":6,"HTV":8,
    "EQK":2,"PND":0,"WAR":0
}

def estimate_income_loss(
    worker_context: dict,
    disruption_code: str,
    model_path: str = "income_loss_qr.pkl",
    rain_mm: float = 0.0,
    aqi_val: float = 0.0,
    wind_speed: float = 0.0,
    vis_m: float = 10000.0,
    temp_c: float = 28.0,
    mag: float = 0.0,
    measured_value: float = 0.0,
    severity: str = "Moderate",
    layers_passed: int = 5,
    distance: float = 0.0,
    flag_count: int = 0,
) -> dict:
    art = _load_artifact(model_path)
    models = art["models"]
    scaler = art["scaler"]
    feats = art["feature_cols"]
    dur_map = art.get("duration_map", _DURATION_MAP)
    codes = art.get("disruption_codes", list(dur_map.keys()))
    dc_means = art.get("dc_means", {})
    gm = art.get("global_mean", 2000)

    dc = disruption_code
    if dc not in dur_map:
        dc = "HRA"

    # Extract worker features
    avg_del = max(1, worker_context.get("avg_daily_deliveries", 10))
    plat_enc = {"Zomato":1, "Swiggy":0}.get(worker_context.get("platform", "Swiggy"), 0)
    risk_enc = {"high":2, "medium":1, "low":0}.get(worker_context.get("risk", "medium"), 1)
    months = worker_context.get("months_active", 6)
    workdays = worker_context.get("typical_workdays", 5)
    if isinstance(workdays, str):
        workdays = len(workdays.split(",")) if "," in workdays else 5
    past_cl = worker_context.get("past_claims", 0)
    past_cor = worker_context.get("past_correct_claims", 0)
    kavach = worker_context.get("kavachScore", 750)
    weekly_inc = worker_context.get("avg_weekly_income", 3000)
    daily_dist = worker_context.get("avg_daily_distance", 20)
    coverage = worker_context.get("coverage", 2000)
    premium = worker_context.get("premium", 60)
    risk_mult = worker_context.get("risk_multiplier", 1.0)
    sde_enc = {"high":2, "medium":1, "low":0}.get(worker_context.get("social_disruption_exposure", "medium"), 1)
    total_paid = worker_context.get("total_paid", 0)
    age = worker_context.get("age", 28)
    city_tier = worker_context.get("city_tier", 1)

    sev_enc = {"Severe":2, "Moderate":1, "Minor":0}.get(severity, 1)
    dur_hrs = dur_map.get(dc, 6)

    # Derived features
    claim_acc = past_cor / (past_cl + 1)
    daily_inc = weekly_inc / 6
    hourly_inc = daily_inc / 8
    cov_inc_r = coverage / (weekly_inc + 1)
    prem_inc_r = premium / (weekly_inc + 1)
    exp_score = np.log1p(months) * kavach / 900
    del_dens = avg_del / (daily_dist + 1)
    loss_pdel = total_paid / (past_cl + 1)
    hon_score = claim_acc * kavach / 900
    dis_sev = dur_hrs * (1 + risk_enc*0.5) * (1 + sev_enc*0.3)
    rule_loss = (daily_inc * dur_hrs / 8) * (sev_enc * 0.35)

    import datetime
    now = datetime.datetime.now()
    dow = now.weekday()
    mon = now.month

    row = {
        "avg_daily_deliveries": avg_del,
        "platform_enc": plat_enc,
        "risk_enc": risk_enc,
        "months_active": months,
        "workdays_count": workdays,
        "past_claims": past_cl,
        "past_correct_claims": past_cor,
        "claim_accuracy": claim_acc,
        "kavachScore": kavach,
        "avg_weekly_income": weekly_inc,
        "avg_daily_distance": daily_dist,
        "daily_income_est": daily_inc,
        "hourly_income_est": hourly_inc,
        "coverage": coverage,
        "coverage_income_ratio": cov_inc_r,
        "premium": premium,
        "premium_income_ratio": prem_inc_r,
        "risk_multiplier": risk_mult,
        "sde_enc": sde_enc,
        "total_paid": total_paid,
        "experience_score": exp_score,
        "delivery_density": del_dens,
        "loss_per_delivery": loss_pdel,
        "honesty_score": hon_score,
        "disruption_hours": dur_hrs,
        "severity_enc": sev_enc,
        "disruption_severity_score": dis_sev,
        "day_of_week": dow,
        "is_weekend": int(dow >= 5),
        "month": mon,
        "quarter": (mon - 1)//3 + 1,
        "is_monsoon": int(mon in [6,7,8,9]),
        "day_of_week_sin": np.sin(2*np.pi*dow/7),
        "day_of_week_cos": np.cos(2*np.pi*dow/7),
        "month_sin": np.sin(2*np.pi*mon/12),
        "month_cos": np.cos(2*np.pi*mon/12),
        "rain_mm": rain_mm,
        "aqi_val": aqi_val,
        "wind_speed": wind_speed,
        "vis_m": vis_m,
        "temp_c": temp_c,
        "mag": mag,
        "measured_value": measured_value,
        "delivery_x_hours": avg_del * dur_hrs,
        "severity_x_delivery": sev_enc * avg_del,
        "severity_x_hours": sev_enc * dur_hrs,
        "income_x_disruption": daily_inc * dur_hrs,
        "income_x_severity": daily_inc * sev_enc,
        "coverage_x_severity": coverage * sev_enc,
        "risk_x_duration": risk_enc * dur_hrs,
        "rule_based_loss": rule_loss,
        "dc_target_enc": dc_means.get(dc, gm),
    }
    # Add interaction features if present in training
    if "delivery_x_rain" in feats:
        row["delivery_x_rain"] = avg_del * rain_mm
    if "risk_x_rain" in feats:
        row["risk_x_rain"] = risk_enc * rain_mm
    if "delivery_x_aqi" in feats:
        row["delivery_x_aqi"] = avg_del * aqi_val
    if "risk_x_aqi" in feats:
        row["risk_x_aqi"] = risk_enc * aqi_val
    if "risk_x_wind" in feats:
        row["risk_x_wind"] = risk_enc * wind_speed

    for code in codes:
        row[f"dc_{code}"] = 1 if code == dc else 0

    X_row = pd.DataFrame([row]).reindex(columns=feats, fill_value=0).astype(float)
    X_row_scaled = pd.DataFrame(scaler.transform(X_row), columns=feats)

    p10 = max(0.0, float(np.expm1(models[0.10].predict(X_row_scaled)[0])))
    p50 = max(0.0, float(np.expm1(models[0.50].predict(X_row_scaled)[0])))
    p90 = max(0.0, float(np.expm1(models[0.90].predict(X_row_scaled)[0])))
    p50 = max(p10, p50)
    p90 = max(p50, p90)

    cap = worker_context.get("coverage", coverage)
    p10 = min(p10, cap)
    p50 = min(p50, cap)
    p90 = min(p90, cap)

    return {
        "p10_loss": round(p10),
        "p50_loss": round(p50),
        "p90_loss": round(p90),
        "interval_width": round(p90 - p10),
        "disruption_code": dc,
    }
'''

with open(OUT_PY, "w") as f:
    f.write(inference_code)
print(f"Saved: {OUT_PY}")
print("\nTraining complete. Files ready: income_loss_qr.pkl, kavach_predict.py")

# ============================================================
# DOWNLOAD ONLY income_loss_qr.pkl and kavach_predict.py
# ============================================================

from google.colab import files
import os

# Files to download
files_to_download = ["income_loss_qr.pkl", "kavach_predict.py"]

for fname in files_to_download:
    if os.path.exists(fname):
        files.download(fname)
        print(f"Downloaded: {fname}")
    else:
        print(f"ERROR: {fname} not found. Run the training code first.")

